# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

repository:
  name: pietrolc.github.io
  url: https://github.com/pietrolc/pietrolc.github.io

logo: https://www.pietrolc.com/wp-content/uploads/2019/11/pietrolc_logo_footer.png

#url: 'https://www.pietrolc.com'
title: My C++ coding challenges to boost your skills!
name: PietroLC.com
description: 'Coding challenges for C++ Software Developers'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pietrolc-github-io.pages.dev" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:title
twitter_username: pietrolcdotcom
github_username:  pietrolc

github:
  - is_project_page: false

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-paginate-v2
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-remote-theme
  - jekyll-author
  - jekyll-toc

authors:
  pietrolc:  # Key matching the author name in your posts
    name: "Pietro Luigi Carotenuto"  # Full name
    bio: "Software engineer and watercolor enthusiast."
    url: https://www.pietrolc.com  # Optional

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections:
  featured_categories:
    output: true
    permalink: /category/:name/
  featured_tags:
    output: true
    permalink: /tag/:name/

toc:
  min_level: 1
  max_level: 6
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: true
  profile: false
  startings: [html, head, body]

defaults:
  - scope:
      path: ""
    values:
      toc: true
